### ISSUE TITLE
Tabelki do MYSQL

### ISSUE THREAD

**Issue by Hax3ey** [XCrafters/xcrBungeePerms#3]
Witajcie jeśli posiadacie już tabeli do wszystkich pluginów udostępnionych ale potraficie to zrobić możecie podlinkować? Z góry dzięki :)

**Comment by MichalPrusak** [comment]
Jak bede w domu to ci podesle wszystko co potrzeba, zaczekaj tak do 15 albo 16 po poludniu :)

**Comment by Hax3ey** [comment]
Ok dzięki Michał :)

**Comment by logixdev** [comment]
@MichalPrusak również czekam i z góry dziękuję. :)

**Comment by Hax3ey** [comment]
@MichalPrusak doczekamy się tych tabelek? :D

**Comment by defabricated** [comment]
Jak ktoś zrobi te tabelki, to niech dopisze w pluginie automatyczne tworzenie struktury w MySQL, bo z tego co widzę jeżeli koledzy nie umieją sobie wyciągnąć tego z pluginu to problem będą mieli również z ich zaimportowaniem. Zamykam.
