### ISSUE TITLE
Kolejny raz piszę ;) Tabelki

### ISSUE THREAD

**Issue by Hax3ey** [XCrafters/xcrBungeePerms#4]
@MichalPrusak Wcześniejszego issues zamknoł defabri więc otwieram nowy jak możesz podlinkuj tabelki do tych plg bo czekamy z utęsknieniem na nie od wczoraj :)

**Comment by defabricated** [comment]
Zamykam i to. Naucz się czytać, jak ktoś zrobi tabelki to ma je wrzucić jako pull request.

**Comment by MichalPrusak** [comment]
Spokojnie. To w zasadzie dwie linijki kodu w onLoad czy onEnable, bo `CREATE TABLE IF NOT EXISTS` nie utworzy tabel jesli beda juz istnialy. Dopisze dzis.
